### PR TITLE
Adding the DTCG logo SVG

### PR DESCRIPTION
**Pull request by donnavitan**
- SVG of Design Tokens Community Group logo
- Can someone put this in an "assets" folder in the root? So we can reference from there?

### CODE REVIEW

**Comment by donnavitan** [comment]
Oh, can we also add the PNG. I'm not familiar with the process here, should I create a new PR? Or can it be included here

logo-dtcg
?

**Comment by donnavitan** [comment]
Oh boop! I grabbed this from one of the chats in Slack. Who has the high-res SVG/PNG for the metal one? Happy to replace!

**Comment by jina** [comment]
the sketch file was posted in the slack a while back so should be in the files menu for the channel

**Comment by kaelig** [comment]
This PR seems to have started from a branch that's now outdated so I'll close it – the PNG should do the trick for now!

**Pull request closed without merging**
